"""Swith numbers to email

Revision ID: 8a9df8c97daa
Revises: 2a9c3ff8d830
Create Date: 2024-10-24 16:21:50.855089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a9df8c97daa'
down_revision: Union[str, None] = '2a9c3ff8d830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('emails', sa.JSON(), nullable=True)
    )
    op.drop_table('number')
    op.add_column('message', sa.Column('emails', sa.JSON(), nullable=True))
    op.drop_column('message', 'numbers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('numbers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('message', 'emails')
    op.create_table('number',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numbers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    op.drop_table('email')
    # ### end Alembic commands ###
