"""Delited number table

Revision ID: 9295d6551a97
Revises: dab29e0abbc2
Create Date: 2024-10-18 22:10:32.993681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9295d6551a97'
down_revision: Union[str, None] = 'dab29e0abbc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('number',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('numbers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='number_pkey')
    )
    # ### end Alembic commands ###
