"""Database creation

Revision ID: 99bf05de062e
Revises: 
Create Date: 2024-10-15 12:50:46.462554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99bf05de062e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numbers', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('numbers_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['numbers_id'], ['numbers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',

    )
    op.drop_table('users')
    op.drop_table('numbers')
    # ### end Alembic commands ###
